

* Things to work on next
** Leverage fuse.Debug but connecting things up in config.
** Bug: in gdrive if I create a test folder with containing to children with the same name, and then ls it, I see both but they appear to have the same inode number.  I see that .dump conains reasonable stuff.  I think this is happening:

   . I return 2 correct direntry elements
   . Lookup gets called twice, based on name only
   . Each time I just grab the first entry and return that as a result of the Lookup call, so it ends up with the same Inode
   . I wonder what happens if I just don't implement Lookup.  It doesn't make sense if a directory can contain two files with the same name

** Make the repo public
   . Figure out the discconnect between the fact that gdrive names its files directly and posix separates inodes from names, allowing for symlinks and hardlinks
   . Move client json file somewhere else
   . document how to get started with this thing
   . looks like I deleted the code that directs the user to point their browser at a url to get a credential.  put it back
** Understand kernel caching and how to work with it.
   . I think the kernel can cache (and even prefetch) content.  How do I take advantage of that?

   . How do I then notify the kernel of changes that happen so it can invalidate?

   . Also, can we automatically notify the system of changes so uis can magically update?  See https://github.com/camlistore/camlistore/issues/244
** I'm locking upward on writes and basically not locking properly when going downward on dump.  fix that.
 
* Things to work on at some point
** consider tracking last-viewed time as attr atime
** Umm, write mode
** Can we reduce change notification spam by filtering out fields we don't care about?
** Allow live configuration via writing to a magic file?  Could turn on and off logging etc.
** Do something useful with file modes
** Have some kind of /recent directory with symlinks to the actual nodes
** Track last-read-time of nodes, evict old ones to save memory
